---
- name: Set sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    sysctl_set: true
    state: "{{ item.state | default('present') }}"
  with_items: "{{ sysctl_settings }}"
